#!/bin/ash

#Mount all drives
#mount -t tmpfs -o size=64k,mode=0755 tmpfs /dev
#mkdir /dev/pts
#mount -t devpts devpts /dev/pts
#mount -t proc proc /proc
#mount -t sysfs sysfs /sys
#echo /sbin/mdev > /proc/sys/kernel/hotplug
#mdev -s

mount -t proc none /proc
mount -t sysfs none /sys

rm -rf /tmp/*

hostname -F /etc/hostname

grep -h MODALIAS /sys/bus/*/devices/*/uevent 2> /dev/null | cut -d= -f2 | sort -u | xargs modprobe -abq 2> /dev/null

wpa_supplicant -B -i mlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf
